---
# Add Proxmox LXC container
# Documentation: https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_module.html

- name: Add {{ distribution }} LXC container {{ lxchostname }}.{{ lxcdomain }}
  community.general.proxmox:
    proxmox_default_behavior: no_defaults
    vmid: "{{ vmid }}"  # omit is not possible yet. We need to store the new id in that case (register)
    api_host: "{{ proxmoxhost | default(ansible_hostname) }}.{{ proxmoxdomain | default(ansible_domain) }}"
    api_user: root@pam
    api_password: "{{ proxmox_password }}"
    node: "{{ proxmoxhost | default(ansible_hostname) }}"
    hostname: "{{ lxchostname }}.{{ lxcdomain }}"
    cores: "{{ cores | default(1) }}"
    cpus: '0'
    cpuunits: "{{ cpuunits }}"
    memory: "{{ memory }}"
    swap: "{{ swap }}"
    disk: "{{ storage | default('local') }}:{{ disksize }},mountoptions=noatime"
    pubkey: "{{ lookup('file', '~/Nextcloud/config/ssh/authorized_keys') }}"
    password: "{{ ct_password }}"
    ostemplate: "{{ ostemplate }}"
    netif: "{{ netif }}"
    nameserver: "{{ lxcnameserver | default(omit) }}"
    searchdomain: "{{ lxcdomain }}"
    unprivileged: "{{ unprivileged }}"
    onboot: true
    features: "{{ features }}"
