---
# This block will run when executing on a Proxmox server (or any Debian/Ubuntu family)
- name: Requirements (Debian family).
  block:
  - name: Ensure Python module proxmoxer is installed (apt).
    ansible.builtin.apt:
      name: python3-proxmoxer
      state: present

  - name: Ensure Python module requests is installed (apt).
    ansible.builtin.apt:
      name: python3-requests
      state: present
  when: ansible_os_family == "Debian"

# This block runs when executing on Fedora/CentOS/RedHat (never Proxmox).
- name: Requirements (Red Hat family).
  block:
  - name: Ensure pip is available (dnf).
    ansible.builtin.dnf:
      name: python3-pip
      state: present

  - name: Ensure Python module proxmoxer is installed (pip).
    ansible.builtin.pip:
      name: proxmoxer
      state: present

  - name: Ensure Python module requests is installed (dnf).
    ansible.builtin.dnf:
      name: python3-requests
      state: present
  when: ansible_os_family == "RedHat"